//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34209.
// 
#pragma warning disable 1591

namespace CrmConsoleClient.DMFService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IDMFService", Namespace="http://tempuri.org/")]
    public partial class DMFService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetAllNSOImpactOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOneNSOImpactOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateNSOImpactOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllNSOOutcomeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOneNSOOutcomeOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateNSOOutcomeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllNSOOutputOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOneNSOOutputOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateNSOOutputOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public DMFService() {
            this.Url = global::CrmConsoleClient.Properties.Settings.Default.CrmConsoleClient_DMFService_DMFService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetAllNSOImpactCompletedEventHandler GetAllNSOImpactCompleted;
        
        /// <remarks/>
        public event GetOneNSOImpactCompletedEventHandler GetOneNSOImpactCompleted;
        
        /// <remarks/>
        public event UpdateNSOImpactCompletedEventHandler UpdateNSOImpactCompleted;
        
        /// <remarks/>
        public event GetAllNSOOutcomeCompletedEventHandler GetAllNSOOutcomeCompleted;
        
        /// <remarks/>
        public event GetOneNSOOutcomeCompletedEventHandler GetOneNSOOutcomeCompleted;
        
        /// <remarks/>
        public event UpdateNSOOutcomeCompletedEventHandler UpdateNSOOutcomeCompleted;
        
        /// <remarks/>
        public event GetAllNSOOutputCompletedEventHandler GetAllNSOOutputCompleted;
        
        /// <remarks/>
        public event GetOneNSOOutputCompletedEventHandler GetOneNSOOutputCompleted;
        
        /// <remarks/>
        public event UpdateNSOOutputCompletedEventHandler UpdateNSOOutputCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IDMFService/GetAllNSOImpact", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/CRMProxyService.Entity")]
        public ProxyNSOImpact[] GetAllNSOImpact() {
            object[] results = this.Invoke("GetAllNSOImpact", new object[0]);
            return ((ProxyNSOImpact[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllNSOImpactAsync() {
            this.GetAllNSOImpactAsync(null);
        }
        
        /// <remarks/>
        public void GetAllNSOImpactAsync(object userState) {
            if ((this.GetAllNSOImpactOperationCompleted == null)) {
                this.GetAllNSOImpactOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllNSOImpactOperationCompleted);
            }
            this.InvokeAsync("GetAllNSOImpact", new object[0], this.GetAllNSOImpactOperationCompleted, userState);
        }
        
        private void OnGetAllNSOImpactOperationCompleted(object arg) {
            if ((this.GetAllNSOImpactCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllNSOImpactCompleted(this, new GetAllNSOImpactCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IDMFService/GetOneNSOImpact", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ProxyNSOImpact GetOneNSOImpact(string id) {
            object[] results = this.Invoke("GetOneNSOImpact", new object[] {
                        id});
            return ((ProxyNSOImpact)(results[0]));
        }
        
        /// <remarks/>
        public void GetOneNSOImpactAsync(string id) {
            this.GetOneNSOImpactAsync(id, null);
        }
        
        /// <remarks/>
        public void GetOneNSOImpactAsync(string id, object userState) {
            if ((this.GetOneNSOImpactOperationCompleted == null)) {
                this.GetOneNSOImpactOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOneNSOImpactOperationCompleted);
            }
            this.InvokeAsync("GetOneNSOImpact", new object[] {
                        id}, this.GetOneNSOImpactOperationCompleted, userState);
        }
        
        private void OnGetOneNSOImpactOperationCompleted(object arg) {
            if ((this.GetOneNSOImpactCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOneNSOImpactCompleted(this, new GetOneNSOImpactCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IDMFService/UpdateNSOImpact", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateNSOImpact([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] ProxyNSOImpact impact) {
            this.Invoke("UpdateNSOImpact", new object[] {
                        impact});
        }
        
        /// <remarks/>
        public void UpdateNSOImpactAsync(ProxyNSOImpact impact) {
            this.UpdateNSOImpactAsync(impact, null);
        }
        
        /// <remarks/>
        public void UpdateNSOImpactAsync(ProxyNSOImpact impact, object userState) {
            if ((this.UpdateNSOImpactOperationCompleted == null)) {
                this.UpdateNSOImpactOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateNSOImpactOperationCompleted);
            }
            this.InvokeAsync("UpdateNSOImpact", new object[] {
                        impact}, this.UpdateNSOImpactOperationCompleted, userState);
        }
        
        private void OnUpdateNSOImpactOperationCompleted(object arg) {
            if ((this.UpdateNSOImpactCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateNSOImpactCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IDMFService/GetAllNSOOutcome", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/CRMProxyService.Entity")]
        public ProxyNSOOutcome[] GetAllNSOOutcome() {
            object[] results = this.Invoke("GetAllNSOOutcome", new object[0]);
            return ((ProxyNSOOutcome[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllNSOOutcomeAsync() {
            this.GetAllNSOOutcomeAsync(null);
        }
        
        /// <remarks/>
        public void GetAllNSOOutcomeAsync(object userState) {
            if ((this.GetAllNSOOutcomeOperationCompleted == null)) {
                this.GetAllNSOOutcomeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllNSOOutcomeOperationCompleted);
            }
            this.InvokeAsync("GetAllNSOOutcome", new object[0], this.GetAllNSOOutcomeOperationCompleted, userState);
        }
        
        private void OnGetAllNSOOutcomeOperationCompleted(object arg) {
            if ((this.GetAllNSOOutcomeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllNSOOutcomeCompleted(this, new GetAllNSOOutcomeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IDMFService/GetOneNSOOutcome", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ProxyNSOOutcome GetOneNSOOutcome(string id) {
            object[] results = this.Invoke("GetOneNSOOutcome", new object[] {
                        id});
            return ((ProxyNSOOutcome)(results[0]));
        }
        
        /// <remarks/>
        public void GetOneNSOOutcomeAsync(string id) {
            this.GetOneNSOOutcomeAsync(id, null);
        }
        
        /// <remarks/>
        public void GetOneNSOOutcomeAsync(string id, object userState) {
            if ((this.GetOneNSOOutcomeOperationCompleted == null)) {
                this.GetOneNSOOutcomeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOneNSOOutcomeOperationCompleted);
            }
            this.InvokeAsync("GetOneNSOOutcome", new object[] {
                        id}, this.GetOneNSOOutcomeOperationCompleted, userState);
        }
        
        private void OnGetOneNSOOutcomeOperationCompleted(object arg) {
            if ((this.GetOneNSOOutcomeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOneNSOOutcomeCompleted(this, new GetOneNSOOutcomeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IDMFService/UpdateNSOOutcome", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateNSOOutcome([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] ProxyNSOOutcome outcome) {
            this.Invoke("UpdateNSOOutcome", new object[] {
                        outcome});
        }
        
        /// <remarks/>
        public void UpdateNSOOutcomeAsync(ProxyNSOOutcome outcome) {
            this.UpdateNSOOutcomeAsync(outcome, null);
        }
        
        /// <remarks/>
        public void UpdateNSOOutcomeAsync(ProxyNSOOutcome outcome, object userState) {
            if ((this.UpdateNSOOutcomeOperationCompleted == null)) {
                this.UpdateNSOOutcomeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateNSOOutcomeOperationCompleted);
            }
            this.InvokeAsync("UpdateNSOOutcome", new object[] {
                        outcome}, this.UpdateNSOOutcomeOperationCompleted, userState);
        }
        
        private void OnUpdateNSOOutcomeOperationCompleted(object arg) {
            if ((this.UpdateNSOOutcomeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateNSOOutcomeCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IDMFService/GetAllNSOOutput", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/CRMProxyService.Entity")]
        public ProxyNSOOutput[] GetAllNSOOutput() {
            object[] results = this.Invoke("GetAllNSOOutput", new object[0]);
            return ((ProxyNSOOutput[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllNSOOutputAsync() {
            this.GetAllNSOOutputAsync(null);
        }
        
        /// <remarks/>
        public void GetAllNSOOutputAsync(object userState) {
            if ((this.GetAllNSOOutputOperationCompleted == null)) {
                this.GetAllNSOOutputOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllNSOOutputOperationCompleted);
            }
            this.InvokeAsync("GetAllNSOOutput", new object[0], this.GetAllNSOOutputOperationCompleted, userState);
        }
        
        private void OnGetAllNSOOutputOperationCompleted(object arg) {
            if ((this.GetAllNSOOutputCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllNSOOutputCompleted(this, new GetAllNSOOutputCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IDMFService/GetOneNSOOutput", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ProxyNSOOutput GetOneNSOOutput(string id) {
            object[] results = this.Invoke("GetOneNSOOutput", new object[] {
                        id});
            return ((ProxyNSOOutput)(results[0]));
        }
        
        /// <remarks/>
        public void GetOneNSOOutputAsync(string id) {
            this.GetOneNSOOutputAsync(id, null);
        }
        
        /// <remarks/>
        public void GetOneNSOOutputAsync(string id, object userState) {
            if ((this.GetOneNSOOutputOperationCompleted == null)) {
                this.GetOneNSOOutputOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOneNSOOutputOperationCompleted);
            }
            this.InvokeAsync("GetOneNSOOutput", new object[] {
                        id}, this.GetOneNSOOutputOperationCompleted, userState);
        }
        
        private void OnGetOneNSOOutputOperationCompleted(object arg) {
            if ((this.GetOneNSOOutputCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOneNSOOutputCompleted(this, new GetOneNSOOutputCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IDMFService/UpdateNSOOutput", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateNSOOutput([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] ProxyNSOOutput output) {
            this.Invoke("UpdateNSOOutput", new object[] {
                        output});
        }
        
        /// <remarks/>
        public void UpdateNSOOutputAsync(ProxyNSOOutput output) {
            this.UpdateNSOOutputAsync(output, null);
        }
        
        /// <remarks/>
        public void UpdateNSOOutputAsync(ProxyNSOOutput output, object userState) {
            if ((this.UpdateNSOOutputOperationCompleted == null)) {
                this.UpdateNSOOutputOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateNSOOutputOperationCompleted);
            }
            this.InvokeAsync("UpdateNSOOutput", new object[] {
                        output}, this.UpdateNSOOutputOperationCompleted, userState);
        }
        
        private void OnUpdateNSOOutputOperationCompleted(object arg) {
            if ((this.UpdateNSOOutputCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateNSOOutputCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34283")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/CRMProxyService.Entity")]
    public partial class ProxyNSOImpact {
        
        private string achievedByYearField;
        
        private System.Nullable<double> achievementValueField;
        
        private bool achievementValueFieldSpecified;
        
        private string actionTakenField;
        
        private string assessmentOfCurrentStatusField;
        
        private string assumptionsField;
        
        private System.Nullable<int> baselineValueField;
        
        private bool baselineValueFieldSpecified;
        
        private string baselineYearField;
        
        private string classificationField;
        
        private System.Nullable<bool> cumulativeValueField;
        
        private bool cumulativeValueFieldSpecified;
        
        private System.Nullable<System.DateTime> dateField;
        
        private bool dateFieldSpecified;
        
        private string idField;
        
        private string impactNoField;
        
        private string impactStatementField;
        
        private string indicatorsField;
        
        private System.Nullable<System.DateTime> modifiedOnField;
        
        private bool modifiedOnFieldSpecified;
        
        private string opportunityIDField;
        
        private string opportunityIDStringField;
        
        private System.Nullable<double> performanceTargetsField;
        
        private bool performanceTargetsFieldSpecified;
        
        private string problemsField;
        
        private string progressStatusField;
        
        private string recentDevelopmentField;
        
        private System.Nullable<System.DateTime> reportingEndDateField;
        
        private bool reportingEndDateFieldSpecified;
        
        private System.Nullable<System.DateTime> reportingStartDateField;
        
        private bool reportingStartDateFieldSpecified;
        
        private string riskAssessmentOfCurrentStatusField;
        
        private string risksField;
        
        private string unitOfMeasurementField;
        
        private System.Nullable<double> valueField;
        
        private bool valueFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AchievedByYear {
            get {
                return this.achievedByYearField;
            }
            set {
                this.achievedByYearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> AchievementValue {
            get {
                return this.achievementValueField;
            }
            set {
                this.achievementValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AchievementValueSpecified {
            get {
                return this.achievementValueFieldSpecified;
            }
            set {
                this.achievementValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ActionTaken {
            get {
                return this.actionTakenField;
            }
            set {
                this.actionTakenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AssessmentOfCurrentStatus {
            get {
                return this.assessmentOfCurrentStatusField;
            }
            set {
                this.assessmentOfCurrentStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Assumptions {
            get {
                return this.assumptionsField;
            }
            set {
                this.assumptionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> BaselineValue {
            get {
                return this.baselineValueField;
            }
            set {
                this.baselineValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BaselineValueSpecified {
            get {
                return this.baselineValueFieldSpecified;
            }
            set {
                this.baselineValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string BaselineYear {
            get {
                return this.baselineYearField;
            }
            set {
                this.baselineYearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Classification {
            get {
                return this.classificationField;
            }
            set {
                this.classificationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> CumulativeValue {
            get {
                return this.cumulativeValueField;
            }
            set {
                this.cumulativeValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CumulativeValueSpecified {
            get {
                return this.cumulativeValueFieldSpecified;
            }
            set {
                this.cumulativeValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateSpecified {
            get {
                return this.dateFieldSpecified;
            }
            set {
                this.dateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ImpactNo {
            get {
                return this.impactNoField;
            }
            set {
                this.impactNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ImpactStatement {
            get {
                return this.impactStatementField;
            }
            set {
                this.impactStatementField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Indicators {
            get {
                return this.indicatorsField;
            }
            set {
                this.indicatorsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> ModifiedOn {
            get {
                return this.modifiedOnField;
            }
            set {
                this.modifiedOnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ModifiedOnSpecified {
            get {
                return this.modifiedOnFieldSpecified;
            }
            set {
                this.modifiedOnFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string OpportunityID {
            get {
                return this.opportunityIDField;
            }
            set {
                this.opportunityIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string OpportunityIDString {
            get {
                return this.opportunityIDStringField;
            }
            set {
                this.opportunityIDStringField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> PerformanceTargets {
            get {
                return this.performanceTargetsField;
            }
            set {
                this.performanceTargetsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PerformanceTargetsSpecified {
            get {
                return this.performanceTargetsFieldSpecified;
            }
            set {
                this.performanceTargetsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Problems {
            get {
                return this.problemsField;
            }
            set {
                this.problemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ProgressStatus {
            get {
                return this.progressStatusField;
            }
            set {
                this.progressStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string RecentDevelopment {
            get {
                return this.recentDevelopmentField;
            }
            set {
                this.recentDevelopmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> ReportingEndDate {
            get {
                return this.reportingEndDateField;
            }
            set {
                this.reportingEndDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReportingEndDateSpecified {
            get {
                return this.reportingEndDateFieldSpecified;
            }
            set {
                this.reportingEndDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> ReportingStartDate {
            get {
                return this.reportingStartDateField;
            }
            set {
                this.reportingStartDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReportingStartDateSpecified {
            get {
                return this.reportingStartDateFieldSpecified;
            }
            set {
                this.reportingStartDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string RiskAssessmentOfCurrentStatus {
            get {
                return this.riskAssessmentOfCurrentStatusField;
            }
            set {
                this.riskAssessmentOfCurrentStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Risks {
            get {
                return this.risksField;
            }
            set {
                this.risksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string UnitOfMeasurement {
            get {
                return this.unitOfMeasurementField;
            }
            set {
                this.unitOfMeasurementField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValueSpecified {
            get {
                return this.valueFieldSpecified;
            }
            set {
                this.valueFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34283")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/CRMProxyService.Entity")]
    public partial class ProxyNSOOutput {
        
        private string achievedByYearField;
        
        private System.Nullable<double> achievementValueField;
        
        private bool achievementValueFieldSpecified;
        
        private string actionTakenField;
        
        private string assessmentOfCurrentStatusField;
        
        private string assumptionsField;
        
        private System.Nullable<double> baselineValueField;
        
        private bool baselineValueFieldSpecified;
        
        private string baselineYearField;
        
        private string classificationField;
        
        private System.Nullable<bool> cumulativeValueField;
        
        private bool cumulativeValueFieldSpecified;
        
        private System.Nullable<System.DateTime> dateField;
        
        private bool dateFieldSpecified;
        
        private string idField;
        
        private string indicatorsField;
        
        private System.Nullable<System.DateTime> modifiedOnField;
        
        private bool modifiedOnFieldSpecified;
        
        private string opportunityIDField;
        
        private string opportunityIDStringField;
        
        private string outputNoField;
        
        private string outputStatementField;
        
        private System.Nullable<double> performanceTargetsField;
        
        private bool performanceTargetsFieldSpecified;
        
        private string problemsField;
        
        private string progressStatusField;
        
        private string recentDevelopmentField;
        
        private System.Nullable<System.DateTime> reportingEndDateField;
        
        private bool reportingEndDateFieldSpecified;
        
        private System.Nullable<System.DateTime> reportingStartDateField;
        
        private bool reportingStartDateFieldSpecified;
        
        private string riskAssessmentOfCurrentStatusField;
        
        private string risksField;
        
        private string unitOfMeasurementField;
        
        private System.Nullable<double> valueField;
        
        private bool valueFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AchievedByYear {
            get {
                return this.achievedByYearField;
            }
            set {
                this.achievedByYearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> AchievementValue {
            get {
                return this.achievementValueField;
            }
            set {
                this.achievementValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AchievementValueSpecified {
            get {
                return this.achievementValueFieldSpecified;
            }
            set {
                this.achievementValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ActionTaken {
            get {
                return this.actionTakenField;
            }
            set {
                this.actionTakenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AssessmentOfCurrentStatus {
            get {
                return this.assessmentOfCurrentStatusField;
            }
            set {
                this.assessmentOfCurrentStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Assumptions {
            get {
                return this.assumptionsField;
            }
            set {
                this.assumptionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> BaselineValue {
            get {
                return this.baselineValueField;
            }
            set {
                this.baselineValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BaselineValueSpecified {
            get {
                return this.baselineValueFieldSpecified;
            }
            set {
                this.baselineValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string BaselineYear {
            get {
                return this.baselineYearField;
            }
            set {
                this.baselineYearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Classification {
            get {
                return this.classificationField;
            }
            set {
                this.classificationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> CumulativeValue {
            get {
                return this.cumulativeValueField;
            }
            set {
                this.cumulativeValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CumulativeValueSpecified {
            get {
                return this.cumulativeValueFieldSpecified;
            }
            set {
                this.cumulativeValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateSpecified {
            get {
                return this.dateFieldSpecified;
            }
            set {
                this.dateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Indicators {
            get {
                return this.indicatorsField;
            }
            set {
                this.indicatorsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> ModifiedOn {
            get {
                return this.modifiedOnField;
            }
            set {
                this.modifiedOnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ModifiedOnSpecified {
            get {
                return this.modifiedOnFieldSpecified;
            }
            set {
                this.modifiedOnFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string OpportunityID {
            get {
                return this.opportunityIDField;
            }
            set {
                this.opportunityIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string OpportunityIDString {
            get {
                return this.opportunityIDStringField;
            }
            set {
                this.opportunityIDStringField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string OutputNo {
            get {
                return this.outputNoField;
            }
            set {
                this.outputNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string OutputStatement {
            get {
                return this.outputStatementField;
            }
            set {
                this.outputStatementField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> PerformanceTargets {
            get {
                return this.performanceTargetsField;
            }
            set {
                this.performanceTargetsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PerformanceTargetsSpecified {
            get {
                return this.performanceTargetsFieldSpecified;
            }
            set {
                this.performanceTargetsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Problems {
            get {
                return this.problemsField;
            }
            set {
                this.problemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ProgressStatus {
            get {
                return this.progressStatusField;
            }
            set {
                this.progressStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string RecentDevelopment {
            get {
                return this.recentDevelopmentField;
            }
            set {
                this.recentDevelopmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> ReportingEndDate {
            get {
                return this.reportingEndDateField;
            }
            set {
                this.reportingEndDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReportingEndDateSpecified {
            get {
                return this.reportingEndDateFieldSpecified;
            }
            set {
                this.reportingEndDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> ReportingStartDate {
            get {
                return this.reportingStartDateField;
            }
            set {
                this.reportingStartDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReportingStartDateSpecified {
            get {
                return this.reportingStartDateFieldSpecified;
            }
            set {
                this.reportingStartDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string RiskAssessmentOfCurrentStatus {
            get {
                return this.riskAssessmentOfCurrentStatusField;
            }
            set {
                this.riskAssessmentOfCurrentStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Risks {
            get {
                return this.risksField;
            }
            set {
                this.risksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string UnitOfMeasurement {
            get {
                return this.unitOfMeasurementField;
            }
            set {
                this.unitOfMeasurementField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValueSpecified {
            get {
                return this.valueFieldSpecified;
            }
            set {
                this.valueFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34283")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/CRMProxyService.Entity")]
    public partial class ProxyNSOOutcome {
        
        private string achievedByYearField;
        
        private System.Nullable<double> achievementValueField;
        
        private bool achievementValueFieldSpecified;
        
        private string actionTakenField;
        
        private string assessmentOfCurrentStatusField;
        
        private string assumptionsField;
        
        private System.Nullable<int> baselineValueField;
        
        private bool baselineValueFieldSpecified;
        
        private string baselineYearField;
        
        private string classificationField;
        
        private System.Nullable<bool> cumulativeValueField;
        
        private bool cumulativeValueFieldSpecified;
        
        private System.Nullable<System.DateTime> dateField;
        
        private bool dateFieldSpecified;
        
        private string idField;
        
        private string indicatorsField;
        
        private System.Nullable<System.DateTime> modifiedOnField;
        
        private bool modifiedOnFieldSpecified;
        
        private string opportunityIDField;
        
        private string opportunityIDStringField;
        
        private string outcomeNoField;
        
        private string outcomeStatementField;
        
        private System.Nullable<double> performanceTargetsField;
        
        private bool performanceTargetsFieldSpecified;
        
        private string problemsField;
        
        private string progressStatusField;
        
        private string recentDevelopmentField;
        
        private System.Nullable<System.DateTime> reportingEndDateField;
        
        private bool reportingEndDateFieldSpecified;
        
        private System.Nullable<System.DateTime> reportingStartDateField;
        
        private bool reportingStartDateFieldSpecified;
        
        private string riskAssessmentOfCurrentStatusField;
        
        private string risksField;
        
        private string unitOfMeasurementField;
        
        private System.Nullable<double> valueField;
        
        private bool valueFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AchievedByYear {
            get {
                return this.achievedByYearField;
            }
            set {
                this.achievedByYearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> AchievementValue {
            get {
                return this.achievementValueField;
            }
            set {
                this.achievementValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AchievementValueSpecified {
            get {
                return this.achievementValueFieldSpecified;
            }
            set {
                this.achievementValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ActionTaken {
            get {
                return this.actionTakenField;
            }
            set {
                this.actionTakenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AssessmentOfCurrentStatus {
            get {
                return this.assessmentOfCurrentStatusField;
            }
            set {
                this.assessmentOfCurrentStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Assumptions {
            get {
                return this.assumptionsField;
            }
            set {
                this.assumptionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> BaselineValue {
            get {
                return this.baselineValueField;
            }
            set {
                this.baselineValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BaselineValueSpecified {
            get {
                return this.baselineValueFieldSpecified;
            }
            set {
                this.baselineValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string BaselineYear {
            get {
                return this.baselineYearField;
            }
            set {
                this.baselineYearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Classification {
            get {
                return this.classificationField;
            }
            set {
                this.classificationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> CumulativeValue {
            get {
                return this.cumulativeValueField;
            }
            set {
                this.cumulativeValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CumulativeValueSpecified {
            get {
                return this.cumulativeValueFieldSpecified;
            }
            set {
                this.cumulativeValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateSpecified {
            get {
                return this.dateFieldSpecified;
            }
            set {
                this.dateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Indicators {
            get {
                return this.indicatorsField;
            }
            set {
                this.indicatorsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> ModifiedOn {
            get {
                return this.modifiedOnField;
            }
            set {
                this.modifiedOnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ModifiedOnSpecified {
            get {
                return this.modifiedOnFieldSpecified;
            }
            set {
                this.modifiedOnFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string OpportunityID {
            get {
                return this.opportunityIDField;
            }
            set {
                this.opportunityIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string OpportunityIDString {
            get {
                return this.opportunityIDStringField;
            }
            set {
                this.opportunityIDStringField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string OutcomeNo {
            get {
                return this.outcomeNoField;
            }
            set {
                this.outcomeNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string OutcomeStatement {
            get {
                return this.outcomeStatementField;
            }
            set {
                this.outcomeStatementField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> PerformanceTargets {
            get {
                return this.performanceTargetsField;
            }
            set {
                this.performanceTargetsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PerformanceTargetsSpecified {
            get {
                return this.performanceTargetsFieldSpecified;
            }
            set {
                this.performanceTargetsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Problems {
            get {
                return this.problemsField;
            }
            set {
                this.problemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ProgressStatus {
            get {
                return this.progressStatusField;
            }
            set {
                this.progressStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string RecentDevelopment {
            get {
                return this.recentDevelopmentField;
            }
            set {
                this.recentDevelopmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> ReportingEndDate {
            get {
                return this.reportingEndDateField;
            }
            set {
                this.reportingEndDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReportingEndDateSpecified {
            get {
                return this.reportingEndDateFieldSpecified;
            }
            set {
                this.reportingEndDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> ReportingStartDate {
            get {
                return this.reportingStartDateField;
            }
            set {
                this.reportingStartDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReportingStartDateSpecified {
            get {
                return this.reportingStartDateFieldSpecified;
            }
            set {
                this.reportingStartDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string RiskAssessmentOfCurrentStatus {
            get {
                return this.riskAssessmentOfCurrentStatusField;
            }
            set {
                this.riskAssessmentOfCurrentStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Risks {
            get {
                return this.risksField;
            }
            set {
                this.risksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string UnitOfMeasurement {
            get {
                return this.unitOfMeasurementField;
            }
            set {
                this.unitOfMeasurementField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValueSpecified {
            get {
                return this.valueFieldSpecified;
            }
            set {
                this.valueFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetAllNSOImpactCompletedEventHandler(object sender, GetAllNSOImpactCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllNSOImpactCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllNSOImpactCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ProxyNSOImpact[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProxyNSOImpact[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetOneNSOImpactCompletedEventHandler(object sender, GetOneNSOImpactCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOneNSOImpactCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOneNSOImpactCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ProxyNSOImpact Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProxyNSOImpact)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void UpdateNSOImpactCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetAllNSOOutcomeCompletedEventHandler(object sender, GetAllNSOOutcomeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllNSOOutcomeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllNSOOutcomeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ProxyNSOOutcome[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProxyNSOOutcome[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetOneNSOOutcomeCompletedEventHandler(object sender, GetOneNSOOutcomeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOneNSOOutcomeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOneNSOOutcomeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ProxyNSOOutcome Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProxyNSOOutcome)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void UpdateNSOOutcomeCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetAllNSOOutputCompletedEventHandler(object sender, GetAllNSOOutputCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllNSOOutputCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllNSOOutputCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ProxyNSOOutput[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProxyNSOOutput[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetOneNSOOutputCompletedEventHandler(object sender, GetOneNSOOutputCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOneNSOOutputCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOneNSOOutputCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ProxyNSOOutput Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProxyNSOOutput)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void UpdateNSOOutputCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591