//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34209.
// 
#pragma warning disable 1591

namespace CrmConsoleClient.CovenantService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_ICovenantService", Namespace="http://tempuri.org/")]
    public partial class CovenantService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetAllSOVCovenantOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOneSOVCovenantOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllNSOCovenantOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOneNSOCovenantOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CovenantService() {
            this.Url = global::CrmConsoleClient.Properties.Settings.Default.CrmConsoleClient_CovenantService_CovenantService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetAllSOVCovenantCompletedEventHandler GetAllSOVCovenantCompleted;
        
        /// <remarks/>
        public event GetOneSOVCovenantCompletedEventHandler GetOneSOVCovenantCompleted;
        
        /// <remarks/>
        public event GetAllNSOCovenantCompletedEventHandler GetAllNSOCovenantCompleted;
        
        /// <remarks/>
        public event GetOneNSOCovenantCompletedEventHandler GetOneNSOCovenantCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ICovenantService/GetAllSOVCovenant", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/CRMProxyService.Entity")]
        public ProxySOVCovenant[] GetAllSOVCovenant() {
            object[] results = this.Invoke("GetAllSOVCovenant", new object[0]);
            return ((ProxySOVCovenant[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllSOVCovenantAsync() {
            this.GetAllSOVCovenantAsync(null);
        }
        
        /// <remarks/>
        public void GetAllSOVCovenantAsync(object userState) {
            if ((this.GetAllSOVCovenantOperationCompleted == null)) {
                this.GetAllSOVCovenantOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllSOVCovenantOperationCompleted);
            }
            this.InvokeAsync("GetAllSOVCovenant", new object[0], this.GetAllSOVCovenantOperationCompleted, userState);
        }
        
        private void OnGetAllSOVCovenantOperationCompleted(object arg) {
            if ((this.GetAllSOVCovenantCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllSOVCovenantCompleted(this, new GetAllSOVCovenantCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ICovenantService/GetOneSOVCovenant", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ProxySOVCovenant GetOneSOVCovenant(string id) {
            object[] results = this.Invoke("GetOneSOVCovenant", new object[] {
                        id});
            return ((ProxySOVCovenant)(results[0]));
        }
        
        /// <remarks/>
        public void GetOneSOVCovenantAsync(string id) {
            this.GetOneSOVCovenantAsync(id, null);
        }
        
        /// <remarks/>
        public void GetOneSOVCovenantAsync(string id, object userState) {
            if ((this.GetOneSOVCovenantOperationCompleted == null)) {
                this.GetOneSOVCovenantOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOneSOVCovenantOperationCompleted);
            }
            this.InvokeAsync("GetOneSOVCovenant", new object[] {
                        id}, this.GetOneSOVCovenantOperationCompleted, userState);
        }
        
        private void OnGetOneSOVCovenantOperationCompleted(object arg) {
            if ((this.GetOneSOVCovenantCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOneSOVCovenantCompleted(this, new GetOneSOVCovenantCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ICovenantService/GetAllNSOCovenant", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/CRMProxyService.Entity")]
        public ProxyNSOCovenant[] GetAllNSOCovenant() {
            object[] results = this.Invoke("GetAllNSOCovenant", new object[0]);
            return ((ProxyNSOCovenant[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllNSOCovenantAsync() {
            this.GetAllNSOCovenantAsync(null);
        }
        
        /// <remarks/>
        public void GetAllNSOCovenantAsync(object userState) {
            if ((this.GetAllNSOCovenantOperationCompleted == null)) {
                this.GetAllNSOCovenantOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllNSOCovenantOperationCompleted);
            }
            this.InvokeAsync("GetAllNSOCovenant", new object[0], this.GetAllNSOCovenantOperationCompleted, userState);
        }
        
        private void OnGetAllNSOCovenantOperationCompleted(object arg) {
            if ((this.GetAllNSOCovenantCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllNSOCovenantCompleted(this, new GetAllNSOCovenantCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ICovenantService/GetOneNSOCovenant", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ProxyNSOCovenant GetOneNSOCovenant(string id) {
            object[] results = this.Invoke("GetOneNSOCovenant", new object[] {
                        id});
            return ((ProxyNSOCovenant)(results[0]));
        }
        
        /// <remarks/>
        public void GetOneNSOCovenantAsync(string id) {
            this.GetOneNSOCovenantAsync(id, null);
        }
        
        /// <remarks/>
        public void GetOneNSOCovenantAsync(string id, object userState) {
            if ((this.GetOneNSOCovenantOperationCompleted == null)) {
                this.GetOneNSOCovenantOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOneNSOCovenantOperationCompleted);
            }
            this.InvokeAsync("GetOneNSOCovenant", new object[] {
                        id}, this.GetOneNSOCovenantOperationCompleted, userState);
        }
        
        private void OnGetOneNSOCovenantOperationCompleted(object arg) {
            if ((this.GetOneNSOCovenantCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOneNSOCovenantCompleted(this, new GetOneNSOCovenantCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/CRMProxyService.Entity")]
    public partial class ProxySOVCovenant {
        
        private string covenantDescriptionField;
        
        private string covenantIDField;
        
        private string nameField;
        
        private string parentIDField;
        
        private string parentIDStringField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CovenantDescription {
            get {
                return this.covenantDescriptionField;
            }
            set {
                this.covenantDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string CovenantID {
            get {
                return this.covenantIDField;
            }
            set {
                this.covenantIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string ParentID {
            get {
                return this.parentIDField;
            }
            set {
                this.parentIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ParentIDString {
            get {
                return this.parentIDStringField;
            }
            set {
                this.parentIDStringField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/CRMProxyService.Entity")]
    public partial class ProxyNSOCovenant {
        
        private string covenantDescriptionField;
        
        private string covenantIDField;
        
        private string nameField;
        
        private string parentIDField;
        
        private string parentIDStringField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CovenantDescription {
            get {
                return this.covenantDescriptionField;
            }
            set {
                this.covenantDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string CovenantID {
            get {
                return this.covenantIDField;
            }
            set {
                this.covenantIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string ParentID {
            get {
                return this.parentIDField;
            }
            set {
                this.parentIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ParentIDString {
            get {
                return this.parentIDStringField;
            }
            set {
                this.parentIDStringField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetAllSOVCovenantCompletedEventHandler(object sender, GetAllSOVCovenantCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllSOVCovenantCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllSOVCovenantCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ProxySOVCovenant[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProxySOVCovenant[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetOneSOVCovenantCompletedEventHandler(object sender, GetOneSOVCovenantCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOneSOVCovenantCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOneSOVCovenantCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ProxySOVCovenant Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProxySOVCovenant)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetAllNSOCovenantCompletedEventHandler(object sender, GetAllNSOCovenantCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllNSOCovenantCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllNSOCovenantCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ProxyNSOCovenant[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProxyNSOCovenant[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetOneNSOCovenantCompletedEventHandler(object sender, GetOneNSOCovenantCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOneNSOCovenantCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOneNSOCovenantCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ProxyNSOCovenant Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProxyNSOCovenant)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591