//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34209.
// 
#pragma warning disable 1591

namespace CrmConsoleClient.OpportunityService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IOpportunityService", Namespace="http://tempuri.org/")]
    public partial class OpportunityService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetAllOpportunityOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOneOpportunityOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateOpportunityOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public OpportunityService() {
            this.Url = global::CrmConsoleClient.Properties.Settings.Default.CrmConsoleClient_OpportunityService_OpportunityService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetAllOpportunityCompletedEventHandler GetAllOpportunityCompleted;
        
        /// <remarks/>
        public event GetOneOpportunityCompletedEventHandler GetOneOpportunityCompleted;
        
        /// <remarks/>
        public event UpdateOpportunityCompletedEventHandler UpdateOpportunityCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IOpportunityService/GetAllOpportunity", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/CRMProxyService.Entity")]
        public ProxyOpportunity[] GetAllOpportunity() {
            object[] results = this.Invoke("GetAllOpportunity", new object[0]);
            return ((ProxyOpportunity[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllOpportunityAsync() {
            this.GetAllOpportunityAsync(null);
        }
        
        /// <remarks/>
        public void GetAllOpportunityAsync(object userState) {
            if ((this.GetAllOpportunityOperationCompleted == null)) {
                this.GetAllOpportunityOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllOpportunityOperationCompleted);
            }
            this.InvokeAsync("GetAllOpportunity", new object[0], this.GetAllOpportunityOperationCompleted, userState);
        }
        
        private void OnGetAllOpportunityOperationCompleted(object arg) {
            if ((this.GetAllOpportunityCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllOpportunityCompleted(this, new GetAllOpportunityCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IOpportunityService/GetOneOpportunity", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ProxyOpportunity GetOneOpportunity(string id) {
            object[] results = this.Invoke("GetOneOpportunity", new object[] {
                        id});
            return ((ProxyOpportunity)(results[0]));
        }
        
        /// <remarks/>
        public void GetOneOpportunityAsync(string id) {
            this.GetOneOpportunityAsync(id, null);
        }
        
        /// <remarks/>
        public void GetOneOpportunityAsync(string id, object userState) {
            if ((this.GetOneOpportunityOperationCompleted == null)) {
                this.GetOneOpportunityOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOneOpportunityOperationCompleted);
            }
            this.InvokeAsync("GetOneOpportunity", new object[] {
                        id}, this.GetOneOpportunityOperationCompleted, userState);
        }
        
        private void OnGetOneOpportunityOperationCompleted(object arg) {
            if ((this.GetOneOpportunityCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOneOpportunityCompleted(this, new GetOneOpportunityCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IOpportunityService/UpdateOpportunity", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateOpportunity(string id, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] ProxyOpportunity opp, out bool UpdateOpportunityResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool UpdateOpportunityResultSpecified) {
            object[] results = this.Invoke("UpdateOpportunity", new object[] {
                        id,
                        opp});
            UpdateOpportunityResult = ((bool)(results[0]));
            UpdateOpportunityResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void UpdateOpportunityAsync(string id, ProxyOpportunity opp) {
            this.UpdateOpportunityAsync(id, opp, null);
        }
        
        /// <remarks/>
        public void UpdateOpportunityAsync(string id, ProxyOpportunity opp, object userState) {
            if ((this.UpdateOpportunityOperationCompleted == null)) {
                this.UpdateOpportunityOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateOpportunityOperationCompleted);
            }
            this.InvokeAsync("UpdateOpportunity", new object[] {
                        id,
                        opp}, this.UpdateOpportunityOperationCompleted, userState);
        }
        
        private void OnUpdateOpportunityOperationCompleted(object arg) {
            if ((this.UpdateOpportunityCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateOpportunityCompleted(this, new UpdateOpportunityCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34283")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/CRMProxyService.Entity")]
    public partial class ProxyOpportunity {
        
        private decimal aDBFinancingField;
        
        private bool aDBFinancingFieldSpecified;
        
        private string additionalFinancingField;
        
        private string approvalLevelField;
        
        private string borrowerField;
        
        private System.Nullable<decimal> budgetAmountField;
        
        private bool budgetAmountFieldSpecified;
        
        private string categoryTypeField;
        
        private System.Nullable<System.DateTime> closingDateField;
        
        private bool closingDateFieldSpecified;
        
        private string countryField;
        
        private string currencyField;
        
        private string departmentField;
        
        private string descriptionField;
        
        private string divisionField;
        
        private string divisionRoleField;
        
        private string expectedApprovalYearField;
        
        private string guaranteeField;
        
        private string idField;
        
        private string modeOfFinancialAssistanceField;
        
        private string nSCoreSectorField;
        
        private string nSOProcessingCategoryField;
        
        private string nSProjectTypeField;
        
        private string nameField;
        
        private string opportunityIdField;
        
        private string processingCategoryField;
        
        private string projectDescriptionField;
        
        private string projectNoField;
        
        private string projectRationaleField;
        
        private string projectStageField;
        
        private string projectStatusField;
        
        private string regionField;
        
        private string sectorField;
        
        private string subSectorField;
        
        private string taskStatusField;
        
        private string processingScenarioField;
        
        /// <remarks/>
        public decimal ADBFinancing {
            get {
                return this.aDBFinancingField;
            }
            set {
                this.aDBFinancingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ADBFinancingSpecified {
            get {
                return this.aDBFinancingFieldSpecified;
            }
            set {
                this.aDBFinancingFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AdditionalFinancing {
            get {
                return this.additionalFinancingField;
            }
            set {
                this.additionalFinancingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ApprovalLevel {
            get {
                return this.approvalLevelField;
            }
            set {
                this.approvalLevelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Borrower {
            get {
                return this.borrowerField;
            }
            set {
                this.borrowerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> BudgetAmount {
            get {
                return this.budgetAmountField;
            }
            set {
                this.budgetAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BudgetAmountSpecified {
            get {
                return this.budgetAmountFieldSpecified;
            }
            set {
                this.budgetAmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CategoryType {
            get {
                return this.categoryTypeField;
            }
            set {
                this.categoryTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> ClosingDate {
            get {
                return this.closingDateField;
            }
            set {
                this.closingDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ClosingDateSpecified {
            get {
                return this.closingDateFieldSpecified;
            }
            set {
                this.closingDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Department {
            get {
                return this.departmentField;
            }
            set {
                this.departmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Division {
            get {
                return this.divisionField;
            }
            set {
                this.divisionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DivisionRole {
            get {
                return this.divisionRoleField;
            }
            set {
                this.divisionRoleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ExpectedApprovalYear {
            get {
                return this.expectedApprovalYearField;
            }
            set {
                this.expectedApprovalYearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Guarantee {
            get {
                return this.guaranteeField;
            }
            set {
                this.guaranteeField = value;
            }
        }
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ModeOfFinancialAssistance {
            get {
                return this.modeOfFinancialAssistanceField;
            }
            set {
                this.modeOfFinancialAssistanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NSCoreSector {
            get {
                return this.nSCoreSectorField;
            }
            set {
                this.nSCoreSectorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NSOProcessingCategory {
            get {
                return this.nSOProcessingCategoryField;
            }
            set {
                this.nSOProcessingCategoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NSProjectType {
            get {
                return this.nSProjectTypeField;
            }
            set {
                this.nSProjectTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string OpportunityId {
            get {
                return this.opportunityIdField;
            }
            set {
                this.opportunityIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ProcessingCategory {
            get {
                return this.processingCategoryField;
            }
            set {
                this.processingCategoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ProjectDescription {
            get {
                return this.projectDescriptionField;
            }
            set {
                this.projectDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ProjectNo {
            get {
                return this.projectNoField;
            }
            set {
                this.projectNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ProjectRationale {
            get {
                return this.projectRationaleField;
            }
            set {
                this.projectRationaleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ProjectStage {
            get {
                return this.projectStageField;
            }
            set {
                this.projectStageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ProjectStatus {
            get {
                return this.projectStatusField;
            }
            set {
                this.projectStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Region {
            get {
                return this.regionField;
            }
            set {
                this.regionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Sector {
            get {
                return this.sectorField;
            }
            set {
                this.sectorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SubSector {
            get {
                return this.subSectorField;
            }
            set {
                this.subSectorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TaskStatus {
            get {
                return this.taskStatusField;
            }
            set {
                this.taskStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string processingScenario {
            get {
                return this.processingScenarioField;
            }
            set {
                this.processingScenarioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetAllOpportunityCompletedEventHandler(object sender, GetAllOpportunityCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllOpportunityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllOpportunityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ProxyOpportunity[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProxyOpportunity[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetOneOpportunityCompletedEventHandler(object sender, GetOneOpportunityCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOneOpportunityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOneOpportunityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ProxyOpportunity Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProxyOpportunity)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void UpdateOpportunityCompletedEventHandler(object sender, UpdateOpportunityCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateOpportunityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateOpportunityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool UpdateOpportunityResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool UpdateOpportunityResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
}

#pragma warning restore 1591