//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34209.
// 
#pragma warning disable 1591

namespace CrmConsoleClient.ProjectTeamService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IConnectionService", Namespace="http://tempuri.org/")]
    public partial class ConnectionService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetAllConnectionOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOneConnectionOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateOneConnectionOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ConnectionService() {
            this.Url = global::CrmConsoleClient.Properties.Settings.Default.CrmConsoleClient_ProjectTeamService_ConnectionService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetAllConnectionCompletedEventHandler GetAllConnectionCompleted;
        
        /// <remarks/>
        public event GetOneConnectionCompletedEventHandler GetOneConnectionCompleted;
        
        /// <remarks/>
        public event UpdateOneConnectionCompletedEventHandler UpdateOneConnectionCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IConnectionService/GetAllConnection", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/CRMProxyService.Entity")]
        public ProxyConnection[] GetAllConnection() {
            object[] results = this.Invoke("GetAllConnection", new object[0]);
            return ((ProxyConnection[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllConnectionAsync() {
            this.GetAllConnectionAsync(null);
        }
        
        /// <remarks/>
        public void GetAllConnectionAsync(object userState) {
            if ((this.GetAllConnectionOperationCompleted == null)) {
                this.GetAllConnectionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllConnectionOperationCompleted);
            }
            this.InvokeAsync("GetAllConnection", new object[0], this.GetAllConnectionOperationCompleted, userState);
        }
        
        private void OnGetAllConnectionOperationCompleted(object arg) {
            if ((this.GetAllConnectionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllConnectionCompleted(this, new GetAllConnectionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IConnectionService/GetOneConnection", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ProxyConnection GetOneConnection(string id) {
            object[] results = this.Invoke("GetOneConnection", new object[] {
                        id});
            return ((ProxyConnection)(results[0]));
        }
        
        /// <remarks/>
        public void GetOneConnectionAsync(string id) {
            this.GetOneConnectionAsync(id, null);
        }
        
        /// <remarks/>
        public void GetOneConnectionAsync(string id, object userState) {
            if ((this.GetOneConnectionOperationCompleted == null)) {
                this.GetOneConnectionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOneConnectionOperationCompleted);
            }
            this.InvokeAsync("GetOneConnection", new object[] {
                        id}, this.GetOneConnectionOperationCompleted, userState);
        }
        
        private void OnGetOneConnectionOperationCompleted(object arg) {
            if ((this.GetOneConnectionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOneConnectionCompleted(this, new GetOneConnectionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IConnectionService/UpdateOneConnection", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateOneConnection([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] ProxyConnection c) {
            this.Invoke("UpdateOneConnection", new object[] {
                        c});
        }
        
        /// <remarks/>
        public void UpdateOneConnectionAsync(ProxyConnection c) {
            this.UpdateOneConnectionAsync(c, null);
        }
        
        /// <remarks/>
        public void UpdateOneConnectionAsync(ProxyConnection c, object userState) {
            if ((this.UpdateOneConnectionOperationCompleted == null)) {
                this.UpdateOneConnectionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateOneConnectionOperationCompleted);
            }
            this.InvokeAsync("UpdateOneConnection", new object[] {
                        c}, this.UpdateOneConnectionOperationCompleted, userState);
        }
        
        private void OnUpdateOneConnectionOperationCompleted(object arg) {
            if ((this.UpdateOneConnectionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateOneConnectionCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34283")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/CRMProxyService.Entity")]
    public partial class ProxyConnection {
        
        private string accountNameField;
        
        private string address1_CityField;
        
        private string address1_CountryRegionField;
        
        private string address1_StateProvinceField;
        
        private string address1_Street1Field;
        
        private string address1_Street2Field;
        
        private string address1_Street3Field;
        
        private string address1_ZipCodeField;
        
        private string businessPhoneField;
        
        private string emailField;
        
        private string faxField;
        
        private string fullnameField;
        
        private string idField;
        
        private string jobTitleField;
        
        private string mobilePhoneField;
        
        private string nameField;
        
        private string opportunityIdField;
        
        private string preferedMethodofContactField;
        
        private string roleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AccountName {
            get {
                return this.accountNameField;
            }
            set {
                this.accountNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Address1_City {
            get {
                return this.address1_CityField;
            }
            set {
                this.address1_CityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Address1_CountryRegion {
            get {
                return this.address1_CountryRegionField;
            }
            set {
                this.address1_CountryRegionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Address1_StateProvince {
            get {
                return this.address1_StateProvinceField;
            }
            set {
                this.address1_StateProvinceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Address1_Street1 {
            get {
                return this.address1_Street1Field;
            }
            set {
                this.address1_Street1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Address1_Street2 {
            get {
                return this.address1_Street2Field;
            }
            set {
                this.address1_Street2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Address1_Street3 {
            get {
                return this.address1_Street3Field;
            }
            set {
                this.address1_Street3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Address1_ZipCode {
            get {
                return this.address1_ZipCodeField;
            }
            set {
                this.address1_ZipCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string BusinessPhone {
            get {
                return this.businessPhoneField;
            }
            set {
                this.businessPhoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Fax {
            get {
                return this.faxField;
            }
            set {
                this.faxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Fullname {
            get {
                return this.fullnameField;
            }
            set {
                this.fullnameField = value;
            }
        }
        
        /// <remarks/>
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string JobTitle {
            get {
                return this.jobTitleField;
            }
            set {
                this.jobTitleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MobilePhone {
            get {
                return this.mobilePhoneField;
            }
            set {
                this.mobilePhoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string OpportunityId {
            get {
                return this.opportunityIdField;
            }
            set {
                this.opportunityIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PreferedMethodofContact {
            get {
                return this.preferedMethodofContactField;
            }
            set {
                this.preferedMethodofContactField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Role {
            get {
                return this.roleField;
            }
            set {
                this.roleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetAllConnectionCompletedEventHandler(object sender, GetAllConnectionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllConnectionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllConnectionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ProxyConnection[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProxyConnection[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetOneConnectionCompletedEventHandler(object sender, GetOneConnectionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOneConnectionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOneConnectionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ProxyConnection Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProxyConnection)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void UpdateOneConnectionCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591