//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34209.
// 
#pragma warning disable 1591

namespace CrmConsoleClient.TradeFinanceService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_ITradeFinanceService", Namespace="http://tempuri.org/")]
    public partial class TradeFinanceService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AddTradeFinanceOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllTradeFinanaceOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOneTradeFinanceOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateTradeFinanceOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public TradeFinanceService() {
            this.Url = global::CrmConsoleClient.Properties.Settings.Default.CrmConsoleClient_TradeFinanceService_TradeFinanceService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AddTradeFinanceCompletedEventHandler AddTradeFinanceCompleted;
        
        /// <remarks/>
        public event GetAllTradeFinanaceCompletedEventHandler GetAllTradeFinanaceCompleted;
        
        /// <remarks/>
        public event GetOneTradeFinanceCompletedEventHandler GetOneTradeFinanceCompleted;
        
        /// <remarks/>
        public event UpdateTradeFinanceCompletedEventHandler UpdateTradeFinanceCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ITradeFinanceService/AddTradeFinance", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AddTradeFinance([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] ProxyCreditGuaranteeRequest entity) {
            this.Invoke("AddTradeFinance", new object[] {
                        entity});
        }
        
        /// <remarks/>
        public void AddTradeFinanceAsync(ProxyCreditGuaranteeRequest entity) {
            this.AddTradeFinanceAsync(entity, null);
        }
        
        /// <remarks/>
        public void AddTradeFinanceAsync(ProxyCreditGuaranteeRequest entity, object userState) {
            if ((this.AddTradeFinanceOperationCompleted == null)) {
                this.AddTradeFinanceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddTradeFinanceOperationCompleted);
            }
            this.InvokeAsync("AddTradeFinance", new object[] {
                        entity}, this.AddTradeFinanceOperationCompleted, userState);
        }
        
        private void OnAddTradeFinanceOperationCompleted(object arg) {
            if ((this.AddTradeFinanceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddTradeFinanceCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ITradeFinanceService/GetAllTradeFinanace", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/CRMProxyService.Entity")]
        public ProxyCreditGuaranteeRequest[] GetAllTradeFinanace() {
            object[] results = this.Invoke("GetAllTradeFinanace", new object[0]);
            return ((ProxyCreditGuaranteeRequest[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllTradeFinanaceAsync() {
            this.GetAllTradeFinanaceAsync(null);
        }
        
        /// <remarks/>
        public void GetAllTradeFinanaceAsync(object userState) {
            if ((this.GetAllTradeFinanaceOperationCompleted == null)) {
                this.GetAllTradeFinanaceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllTradeFinanaceOperationCompleted);
            }
            this.InvokeAsync("GetAllTradeFinanace", new object[0], this.GetAllTradeFinanaceOperationCompleted, userState);
        }
        
        private void OnGetAllTradeFinanaceOperationCompleted(object arg) {
            if ((this.GetAllTradeFinanaceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllTradeFinanaceCompleted(this, new GetAllTradeFinanaceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ITradeFinanceService/GetOneTradeFinance", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ProxyCreditGuaranteeRequest GetOneTradeFinance(string id) {
            object[] results = this.Invoke("GetOneTradeFinance", new object[] {
                        id});
            return ((ProxyCreditGuaranteeRequest)(results[0]));
        }
        
        /// <remarks/>
        public void GetOneTradeFinanceAsync(string id) {
            this.GetOneTradeFinanceAsync(id, null);
        }
        
        /// <remarks/>
        public void GetOneTradeFinanceAsync(string id, object userState) {
            if ((this.GetOneTradeFinanceOperationCompleted == null)) {
                this.GetOneTradeFinanceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOneTradeFinanceOperationCompleted);
            }
            this.InvokeAsync("GetOneTradeFinance", new object[] {
                        id}, this.GetOneTradeFinanceOperationCompleted, userState);
        }
        
        private void OnGetOneTradeFinanceOperationCompleted(object arg) {
            if ((this.GetOneTradeFinanceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOneTradeFinanceCompleted(this, new GetOneTradeFinanceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ITradeFinanceService/UpdateTradeFinance", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateTradeFinance([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] ProxyCreditGuaranteeRequest entity) {
            this.Invoke("UpdateTradeFinance", new object[] {
                        entity});
        }
        
        /// <remarks/>
        public void UpdateTradeFinanceAsync(ProxyCreditGuaranteeRequest entity) {
            this.UpdateTradeFinanceAsync(entity, null);
        }
        
        /// <remarks/>
        public void UpdateTradeFinanceAsync(ProxyCreditGuaranteeRequest entity, object userState) {
            if ((this.UpdateTradeFinanceOperationCompleted == null)) {
                this.UpdateTradeFinanceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateTradeFinanceOperationCompleted);
            }
            this.InvokeAsync("UpdateTradeFinance", new object[] {
                        entity}, this.UpdateTradeFinanceOperationCompleted, userState);
        }
        
        private void OnUpdateTradeFinanceOperationCompleted(object arg) {
            if ((this.UpdateTradeFinanceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateTradeFinanceCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/CRMProxyService.Entity")]
    public partial class ProxyCreditGuaranteeRequest {
        
        private System.Nullable<double> aDBAmountCoveredField;
        
        private bool aDBAmountCoveredFieldSpecified;
        
        private string applicantNameField;
        
        private string beneficiaryNameField;
        
        private string confirmingBankNameField;
        
        private string goodsField;
        
        private string idField;
        
        private string issuingBankNameField;
        
        private string requestNoField;
        
        private string tenorField;
        
        private System.Nullable<double> totalTransactionValueField;
        
        private bool totalTransactionValueFieldSpecified;
        
        private string typeOfTradeTransactionField;
        
        private System.Nullable<int> typeOfTradeTransactionIDField;
        
        private bool typeOfTradeTransactionIDFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> ADBAmountCovered {
            get {
                return this.aDBAmountCoveredField;
            }
            set {
                this.aDBAmountCoveredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ADBAmountCoveredSpecified {
            get {
                return this.aDBAmountCoveredFieldSpecified;
            }
            set {
                this.aDBAmountCoveredFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ApplicantName {
            get {
                return this.applicantNameField;
            }
            set {
                this.applicantNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string BeneficiaryName {
            get {
                return this.beneficiaryNameField;
            }
            set {
                this.beneficiaryNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ConfirmingBankName {
            get {
                return this.confirmingBankNameField;
            }
            set {
                this.confirmingBankNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Goods {
            get {
                return this.goodsField;
            }
            set {
                this.goodsField = value;
            }
        }
        
        /// <remarks/>
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string IssuingBankName {
            get {
                return this.issuingBankNameField;
            }
            set {
                this.issuingBankNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string RequestNo {
            get {
                return this.requestNoField;
            }
            set {
                this.requestNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Tenor {
            get {
                return this.tenorField;
            }
            set {
                this.tenorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> TotalTransactionValue {
            get {
                return this.totalTransactionValueField;
            }
            set {
                this.totalTransactionValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalTransactionValueSpecified {
            get {
                return this.totalTransactionValueFieldSpecified;
            }
            set {
                this.totalTransactionValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TypeOfTradeTransaction {
            get {
                return this.typeOfTradeTransactionField;
            }
            set {
                this.typeOfTradeTransactionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> TypeOfTradeTransactionID {
            get {
                return this.typeOfTradeTransactionIDField;
            }
            set {
                this.typeOfTradeTransactionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TypeOfTradeTransactionIDSpecified {
            get {
                return this.typeOfTradeTransactionIDFieldSpecified;
            }
            set {
                this.typeOfTradeTransactionIDFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void AddTradeFinanceCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetAllTradeFinanaceCompletedEventHandler(object sender, GetAllTradeFinanaceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllTradeFinanaceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllTradeFinanaceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ProxyCreditGuaranteeRequest[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProxyCreditGuaranteeRequest[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetOneTradeFinanceCompletedEventHandler(object sender, GetOneTradeFinanceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOneTradeFinanceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOneTradeFinanceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ProxyCreditGuaranteeRequest Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProxyCreditGuaranteeRequest)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void UpdateTradeFinanceCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591